In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# **week 1**

In [3]:
torch.__version__

'2.4.1+cu121'

##what is pytorch



*   tensor computation(like numpy) np.array==torch.tensor are equal but we can compute our algorithms more quicker  using GPU which we couldn't did that using numpy
*   train deep neural networks using outograd



##tensor

In [4]:
#scalar
torch.tensor(4)
#zero dimentional tensor

tensor(4)

In [7]:
#vector
torch.tensor([1.0, 2, 3])
#1 dimentional tensor

tensor([1., 2., 3.])

In [8]:
#matrix
torch.tensor([[1,2,3], [4.0,5,6]])
#2 dimentional tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
#column vector
torch.tensor([[1],[2],[3],[4]])

tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
#row vector
torch.tensor([[1,2,3,4]])
#this is more useful than vector which is 1 dimentional data structure when we
#are working with matrices

tensor([[1, 2, 3, 4]])

In [15]:
#N-d tensor
#this is useful in deep learning
torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6]
    ],
        [
            [7,8,9],
            [10,11,12]
        ],
        [
            [1,2,3],
            [1,2,3]
        ]
    ]
)
#in the above code we created 3 dimentional tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 1,  2,  3]]])

##Data type

In [16]:
a=torch.tensor([1,2,3])
b=torch.tensor([1,2,3.])

In [17]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [19]:
#define a tensor with unint8 datatype
a=torch.tensor([1,2,3], dtype=torch.uint8)
a.dtype,a

(torch.uint8, tensor([1, 2, 3], dtype=torch.uint8))

In [20]:
#convert datatype
a=a.type(torch.float16)
a

tensor([1., 2., 3.], dtype=torch.float16)

In [22]:
a=a.short()
a

tensor([1, 2, 3], dtype=torch.int16)

In [23]:
#check device where our tensor is on
a.device

device(type='cpu')

In [24]:
#you have to change your runtime to GPU before running this line
a=torch.tensor([1,2,3], device='cuda')
#this tnsor will be saved on the GPU ram

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [25]:
#convert from GPU to CPU
a=a.cpu

##attributes and methods of tensor

**.shape**

In [28]:
scalar=torch.tensor(1)
vec=torch.tensor([1,2,3])
mat=torch.tensor([[1,2,3],[4,5,6]])
tensor= torch.tensor([[[1,2,3],[4,3,4]],[[4,3.,4],[5,6,7]]])

In [31]:
scalar.shape, vec.shape, mat.shape, tensor.shape

(torch.Size([]), torch.Size([3]), torch.Size([2, 3]), torch.Size([2, 2, 3]))

In [33]:
c,r,cc=tensor.shape
c,r,cc

(2, 2, 3)

In [35]:
tensor.shape[2]

3

**.size()**

In [36]:
tensor.size()

torch.Size([2, 2, 3])

In [37]:
tensor.size(0)

2

**.min(), .max()**

In [38]:
tensor.min()

tensor(1.)

**.mean(), .std()**

In [41]:
#torch can just do this statistical functions on the tensors in the type float or complex
vec.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [40]:
vec.float().mean()

tensor(2.)

In [42]:
vec.float().std()

tensor(1.)

**.t()**

In [44]:
#transpose
#we can just run it on the <= 2 dimentional tensors
mat.t()

tensor([[1, 4],
        [2, 5],
        [3, 6]])

**note:**
functions with _ at the end of them are done inplace. It means the output will be overwrited in the variable.

for example: a.abs_() and a.abs()

##special arrays

In [49]:
torch.ones((1,3)),torch.ones((3)), torch.ones((2,3,4,3))

(tensor([[1., 1., 1.]]),
 tensor([1., 1., 1.]),
 tensor([[[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]]],
 
 
         [[[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]],
 
          [[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]]]]))

In [50]:
torch.zeros((0,3))

tensor([], size=(0, 3))

In [51]:
#identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [55]:
torch.eye(5,4, dtype=torch.int8)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]], dtype=torch.int8)

In [57]:
em=torch.empty(3,3)
em

tensor([[ 7.4175e-09,  4.4823e-41,  1.1918e+23],
        [ 3.3076e-41,  4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00, -1.9832e+02]])

In [58]:
em.fill_(2.2)

tensor([[2.2000, 2.2000, 2.2000],
        [2.2000, 2.2000, 2.2000],
        [2.2000, 2.2000, 2.2000]])

In [59]:
torch.full((3,3),fill_value=8)

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])